/**
 * ZCAC-0011/0013 — MessageBus(application):受控 Agent 通信。
 *
 * 职责:
 *   routing        — 按 toAgent 定向或 broadcast
 *   authorization  — CommunicationPolicy 强制(越权被拒)
 *   persistence    — zcac_messages 表(journal-first)
 *   correlation    — threadId 维护 + replyTo 关联
 *   rate-limit     — maxMessagesPerTask 防消息风暴
 *   handoff        — 任务完成时自动生成结构化上下文给下游
 */

import type {
  AgentMessage,
  AgentMessageType,
  CommunicationPolicy,
} from "../domain/message/agent-message.js";
import { isSendAllowed, CommunicationDeniedError } from "../domain/message/agent-message.js";
import type { Task } from "../domain/task/task.js";
import type { Clock } from "../ports/clock.js";
import type { ClusterEventBus } from "../domain/event/event-bus.js";
import type { MessageRepository } from "../ports/message-repository.js";

export interface MessageBusDeps {
  messages: MessageRepository;
  bus: ClusterEventBus;
  clock: Clock;
  policy?: CommunicationPolicy;
}

export interface SendMessageInput {
  runId: string;
  fromAgent: string;
  toAgent: string;
  type: AgentMessageType;
  content: string;
  taskId?: string;
  threadId?: string;
  replyTo?: string;
  metadata?: Record<string, unknown>;
}

export class MessageBus {
  readonly #policy: CommunicationPolicy;
  /** runId:taskId:fromAgent → count(rate-limit 记账) */
  readonly #sentCount = new Map<string, number>();

  constructor(private readonly deps: MessageBusDeps) {
    this.#policy = deps.policy ?? {};
  }

  /**
   * 发送消息:鉴权 → 限速 → 持久化 → 通知 Event Bus(AGENT_MESSAGE 事件)。
   * 返回完整 AgentMessage;被拒绝时抛 CommunicationDeniedError。
   */
  send(input: SendMessageInput): AgentMessage {
    // 系统生成的 handoff 消息免检(agent 通信策略管 agent,不管系统)
    if (input.type !== "handoff") {
      const policy = this.#policy[input.fromAgent];
      if (!isSendAllowed(this.#policy, input.fromAgent, input.toAgent)) {
        throw new CommunicationDeniedError(
          input.fromAgent,
          input.toAgent,
          policy
            ? `target not in canSendTo (allowed: ${policy.canSendTo.join(", ")})`
            : "no policy for role",
        );
      }

      // rate-limit: per task per sender(handoff 也不计入)
      if (input.taskId) {
        const key = `${input.runId}:${input.taskId}:${input.fromAgent}`;
        const count = this.#sentCount.get(key) ?? 0;
        const limit = policy?.maxMessagesPerTask ?? 10;
        if (count >= limit) {
          throw new CommunicationDeniedError(
            input.fromAgent,
            input.toAgent,
            `rate limit: ${count}/${limit} messages for task ${input.taskId}`,
          );
        }
        this.#sentCount.set(key, count + 1);
      }
    }

    // threadId:显式 > replyTo 的 thread > 新建
    let threadId = input.threadId;
    if (!threadId && input.replyTo) {
      const parent = this.deps.messages.get(input.replyTo);
      threadId = parent?.threadId;
    }
    if (!threadId) {
      threadId = `thread_${crypto.randomUUID().slice(0, 12)}`;
    }

    const message: AgentMessage = {
      id: `msg_${crypto.randomUUID()}`,
      runId: input.runId,
      threadId,
      fromAgent: input.fromAgent,
      toAgent: input.toAgent,
      type: input.type,
      content: input.content,
      ...(input.taskId ? { taskId: input.taskId } : {}),
      ...(input.replyTo ? { replyTo: input.replyTo } : {}),
      createdAt: this.deps.clock.now(),
      ...(input.metadata ? { metadata: input.metadata } : {}),
    };

    this.deps.messages.insert(message);
    // Event Bus 通知(观察面;不驱动控制流)
    // 不发 AGENT_MESSAGE 事件类型 — Message 与 Event 语义分离,
    // Message Bus 的持久化本身就是 source of truth。
    return message;
  }

  /** 获取发给某角色(或某线程/任务)的消息。 */
  getMessages(filter: {
    runId: string;
    toAgent?: string;
    fromAgent?: string;
    threadId?: string;
    taskId?: string;
  }): AgentMessage[] {
    return this.deps.messages.query(filter);
  }

  /** 获取完整线程(按时间排序)。 */
  getThread(threadId: string): AgentMessage[] {
    return this.deps.messages.getByThread(threadId);
  }

  /**
   * Task Handoff(Layer 1):任务完成时自动生成结构化上下文。
   * 下游任务的 prompt 通过 injectHandoffContext() 获取。
   */
  generateHandoff(task: Task): AgentMessage | undefined {
    if (!task.output) return undefined;
    const fromAgent = task.input.role ?? "coder";
    const handoff = this.send({
      runId: task.runId,
      fromAgent,
      toAgent: "*",
      type: "handoff",
      content: JSON.stringify({
        taskId: task.id,
        kind: task.kind,
        summary: task.output.summary ?? task.output.response?.slice(0, 200),
        files: task.output.metadata?.files ?? [],
        artifacts: task.output.artifacts,
      }),
      taskId: task.id,
      metadata: { autoGenerated: true },
    });
    return handoff;
  }

  /**
   * 为下游任务构造 handoff 上下文片段(注入 prompt)。
   * 取该任务全部依赖的 handoff 消息,格式化为可读文本。
   */
  injectHandoffContext(task: Task): string | undefined {
    if (task.dependencies.length === 0) return undefined;
    const sections: string[] = [];
    for (const depId of task.dependencies) {
      const handoffs = this.deps.messages.query({
        runId: task.runId,
        taskId: depId,
      }).filter((m) => m.type === "handoff");
      for (const h of handoffs) {
        try {
          const data = JSON.parse(h.content) as {
            taskId: string;
            kind: string;
            summary?: string;
            files?: string[];
          };
          sections.push(
            [
              `[${data.kind} task completed — ${data.taskId.slice(0, 13)}]`,
              data.summary ?? "",
              ...(data.files && data.files.length > 0
                ? [`Changed files: ${data.files.join(", ")}`]
                : []),
            ].join("\n"),
          );
        } catch {
          // 非结构化 handoff,原样注入
          sections.push(h.content);
        }
      }
    }
    if (sections.length === 0) return undefined;
    return [
      "── Upstream task context (from ZCAC Message Bus) ──",
      ...sections,
      "── End upstream context ──",
      "",
    ].join("\n");
  }

  reply(
    originalMessageId: string,
    fromAgent: string,
    content: string,
  ): AgentMessage {
    const original = this.deps.messages.get(originalMessageId);
    if (!original) throw new Error(`Message not found: ${originalMessageId}`);
    return this.send({
      runId: original.runId,
      fromAgent,
      toAgent: original.fromAgent,
      type: original.type === "question" ? "finding" : "request",
      content,
      taskId: original.taskId,
      threadId: original.threadId,
      replyTo: originalMessageId,
    });
  }
}
